swagger: '2.0'
info:
  title: HTTP API Console zigbeealliance.distributedcomplianceledger.dclgenutil
  name: ''
  description: ''
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
